FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
# We add --legacy-peer-deps to fix the install error
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
